### PR TITLE
Fix/132

### LINKED ISSUE #132: formatPoxAddressToNetwork uses wrong network
`formatPoxAddressToNetwork` uses the deprecated env variable NETWORK to determine the network when formating a btc address.

It should use the selected network by the user.

This is only visible if the user changes the network.

### PR DESCRIPTION
**Pull request by friedger**
This PR
* fixes #132 
* updated dependencies

* builds on top of feat/improve-self-service-extend

### CODE REVIEW

File: src/utils/stacking.ts [hunk 1]
```diff
@@ -12,7 +12,14 @@ export function convertPoxAddressToBtc(network: 'mainnet' | 'testnet') {
...
 }
 
-export const formatPoxAddressToNetwork = convertPoxAddressToBtc(NETWORK);
+export const formatPoxAddressToNetwork = (
+  network: StacksNetwork,
+  poxAddress: ConvertToPoxAddressBtc
+) => {
+  return convertPoxAddressToBtc(network.chainId === ChainID.Mainnet ? 'mainnet' : 'testnet')(
+    poxAddress
+  );
```
Comment (kyranjamie) [inline src/utils/stacking.ts:21]: recommend when helper style

```ts
interface WhenChainIdMap<T> {
  [ChainID.Mainnet]: T;
  [ChainID.Testnet]: T;
}
export function whenChainId(chainId: ChainID) {
  return <T>(chainIdMap: WhenChainIdMap<T>): T => chainIdMap[chainId];
}
```

more robust than ternary and more readable

**Review by kyranjamie — APPROVED** [review]

File: src/utils/stacking.ts (hunk 1 above)
Comment (friedger) [reply src/utils/stacking.ts]: comment addressed
